import type { Metadata } from "next";
import { Manrope, Montserrat, Inter } from "next/font/google";
import "../globals.css";

const manpore = Manrope({
    variable: "--font-manpore",
    weight: ["200", "300", "400", "500", "600", "700", "800"],
    subsets: ["latin"],
});

const montserrat = Montserrat({
    variable: "--font-montserrat",
    weight: ["100","200", "300", "400", "500", "600", "700", "800", "900"],
    subsets: ["latin"],
});

const inter = Inter({
    variable: "--font-inter",
    weight: ["100","200", "300", "400", "500", "600", "700", "800", "900"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manpore.variable} ${montserrat.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
