import type { Metadata } from "next";
import { Manrope, Montserrat, Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const manpore = Manrope({
    variable: "--font-manpore",
    weight: ["200", "300", "400", "500", "600", "700", "800"],
    subsets: ["latin"],
});

const montserrat = Montserrat({
    variable: "--font-montserrat",
    weight: ["100","200","300","400","500","600","700","800","900"],
    subsets: ["latin"],
});

const inter = Inter({
    variable: "--font-inter",
    weight: ["100","200","300","400","500","600","700","800","900"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const FB_PIXEL_ID = "719123840945330";

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
        <body className={`${manpore.variable} ${montserrat.variable} ${inter.variable} antialiased`}>
        <Script
            id="calendly-sdk"
            src="https://assets.calendly.com/assets/external/widget.js"
            strategy="afterInteractive"
        />
        {/* Load Facebook Pixel after hydration */}
        <Script
            id="fb-pixel"
            strategy="afterInteractive"
            dangerouslySetInnerHTML={{
                __html: `
              !function(f,b,e,v,n,t,s){
                if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                n.callMethod.apply(n,arguments):n.queue.push(arguments)};
                if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
                n.queue=[];t=b.createElement(e);t.async=!0;
                t.src=v;s=b.getElementsByTagName(e)[0];
                s.parentNode.insertBefore(t,s)
              }(window, document,'script','https://connect.facebook.net/en_US/fbevents.js');
              fbq('init', '${FB_PIXEL_ID}');
              fbq('track', 'PageView');
            `,
            }}
        />

        {/* No-JS fallback */}
        <noscript>
            <img
                height="1"
                width="1"
                style={{ display: "none" }}
                src={`https://www.facebook.com/tr?id=${FB_PIXEL_ID}&ev=PageView&noscript=1`}
                alt=""
            />
        </noscript>

        <Navbar />
        {children}
        <Footer />

        </body>
        </html>
    );
}
